export enum UserRequestEnum {
  Id = 'id',
  Role = 'role',
  Nickname = 'nickname',
  Email = 'email',
  LastsName = 'lastsName',
  FirsName = 'firsName',
  ServiceIds = 'serviceIds',
  CityIds = 'cityIds',
  Phone = 'phone',
  Gender = 'gender',
  Birthday = 'birthday',
  Avatar = 'avatar',
  InfoYourself = 'infoYourself',
}
