export enum UserResponseEnum {
  Id = 'id',
  Role = 'role',
  Nickname = 'nickname',
  Email = 'email',
  LastsName = 'lastsName',
  FirsName = 'firsName',
  Service = 'service',
  City = 'city',
  Phone = 'phone',
  Gender = 'gender',
  Birthday = 'birthday',
  Avatar = 'avatar',
  InfoYourself = 'infoYourself',
}
